/**
 * sessionStore.ts
 *
 * In-memory state for the currently active training session.
 * Data is held here from "Start Session" until the session-complete
 * Edge Function acknowledges the write — at that point the store is cleared.
 *
 * No persistence: if the app is force-quit mid-session the in-progress
 * data is lost. Optimistic session resumption is a Stage 11 concern.
 */

import { create } from 'zustand';
import type { LoggedSet, PlannedExercise, SessionType } from '../types/athlete';

/** All sets logged for a single exercise during the current session. */
interface ExerciseLog {
  exercise: PlannedExercise;
  sets: LoggedSet[];
}

interface SessionStore {
  /** Whether a session is currently in progress. */
  isActive: boolean;
  sessionType: SessionType | null;
  /** ISO timestamp of when the athlete tapped Start Session. */
  startedAt: string | null;
  /** Exercises in slot order for this session, as generated by the engine. */
  plannedExercises: PlannedExercise[];
  /** Logs keyed by exercise name. Populated as sets are logged. */
  exerciseLogs: Record<string, ExerciseLog>;
  /** 0-based index of the exercise currently expanded. */
  currentExerciseIndex: number;
  /** Overall session RPE (1–10) collected at session end. */
  sessionRpe: number | null;
  /** True after a session is successfully saved today. Persists across clearSession. */
  todaySessionComplete: boolean;

  /** Initialise the store for a new session. */
  startSession: (sessionType: SessionType, exercises: PlannedExercise[]) => void;

  /**
   * Append a logged set for the given exercise.
   * Creates the ExerciseLog entry if it doesn't exist yet.
   */
  logSet: (exerciseName: string, set: LoggedSet) => void;

  /** Replace a previously logged set at the given 0-based index. */
  editSet: (exerciseName: string, setIndex: number, updatedSet: LoggedSet) => void;

  /** Advance the expanded exercise to the next slot. */
  advanceExercise: () => void;

  /** Record the post-session overall RPE. */
  setSessionRpe: (rpe: number) => void;

  /** Mark today's session as successfully saved. Does not clear session data. */
  setSessionComplete: () => void;

  /** Reset all session state after a session is completed or discarded. */
  clearSession: () => void;
}

const INITIAL_STATE: Pick<
  SessionStore,
  | 'isActive'
  | 'sessionType'
  | 'startedAt'
  | 'plannedExercises'
  | 'exerciseLogs'
  | 'currentExerciseIndex'
  | 'sessionRpe'
> = {
  isActive: false,
  sessionType: null,
  startedAt: null,
  plannedExercises: [],
  exerciseLogs: {},
  currentExerciseIndex: 0,
  sessionRpe: null,
};
// todaySessionComplete is intentionally excluded from INITIAL_STATE so that
// clearSession() does not reset it — it must persist until the next calendar day.

export const useSessionStore = create<SessionStore>((set, get) => ({
  ...INITIAL_STATE,
  todaySessionComplete: false,

  startSession: (sessionType, exercises) =>
    set({
      isActive: true,
      sessionType,
      startedAt: new Date().toISOString(),
      plannedExercises: exercises,
      exerciseLogs: {},
      currentExerciseIndex: 0,
      sessionRpe: null,
    }),

  logSet: (exerciseName, loggedSet) =>
    set((state) => {
      const existing = state.exerciseLogs[exerciseName];
      const exercise =
        existing?.exercise ??
        state.plannedExercises.find((e) => e.name === exerciseName);

      if (!exercise) return state; // guard against unknown exercise names

      const updatedLog: ExerciseLog = {
        exercise,
        sets: [...(existing?.sets ?? []), loggedSet],
      };

      return {
        exerciseLogs: {
          ...state.exerciseLogs,
          [exerciseName]: updatedLog,
        },
      };
    }),

  editSet: (exerciseName, setIndex, updatedSet) =>
    set((state) => {
      const existing = state.exerciseLogs[exerciseName];
      if (!existing) return state;
      const sets = [...existing.sets];
      sets[setIndex] = updatedSet;
      return {
        exerciseLogs: {
          ...state.exerciseLogs,
          [exerciseName]: { ...existing, sets },
        },
      };
    }),

  advanceExercise: () =>
    set((state) => ({
      currentExerciseIndex: Math.min(
        state.currentExerciseIndex + 1,
        state.plannedExercises.length - 1,
      ),
    })),

  setSessionRpe: (rpe) => set({ sessionRpe: rpe }),

  setSessionComplete: () => set({ todaySessionComplete: true }),

  clearSession: () => set({ ...INITIAL_STATE }),
}));
